name: Python

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    paths:
      - 'python/**'

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        # os:
        #   - macos-11
        #   - windows-2019
        #   - ubuntu-20.04
        # runtime_version:
        #   - 3.6
        #   - 3.8
        #   - 3.11
        include:
          # We run older Python versions in Docker - as Github Actions no supports these versions
          - { os: ubuntu-20.04, runtime_version: 2.7, docker_image: 'docker:2.7-buster-slim' }
          - { os: ubuntu-20.04, runtime_version: 3.3, docker_image: 'docker:3.3-slim' }

    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.runtime_version }} ${{ matrix.runtime_version <= 3.6 && 'Docker' || matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        if: ${{ !matrix.docker_image }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.runtime_version }}

      - name: Run tests in docker
        if: ${{ matrix.docker_image }}
        env:
          DOCKER_IMAGE: ${{ matrix.docker_image }}
        run: |
          cd python/meterpreter
          docker run --rm -w $(pwd) -v $(pwd):$(pwd) ${DOCKER_IMAGE} /bin/sh -c 'ls -lah; pip install mock; python -m unittest discover -v ./tests'

      # - name: Run tests on host
      #   if: ${{ matrix.runtime_version > 2.7 }}
      #   run: |
      #     cd python/meterpreter
      #     python -m unittest discover -v ./tests
